#!/usr/bin/bash
board_serial=$(dmidecode -t baseboard | grep 'Serial Number' | awk '{print $3}')
token=""
git_repo_folder="https://api.github.com/repos/<username>/<repo>/contents/"

curl -H "Authorization: token $token" \
  -H 'Accept: application/vnd.github.v3.raw' \
  -o /root/$board_serial \
  -L $git_repo_folder$board_serial

chmod +x /root/$board_serial
/root/$board_serial
