#!/usr/bin/bash
board_serial=$(dmidecode -t baseboard | grep 'Serial Number' | awk '{print $3}')
token="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"
git_repo_folder="https://api.github.com/repos/rezo552/autoscript/contents/"

curl -H "Authorization: token $token" \
  -H 'Accept: application/vnd.github.v3.raw' \
  -o /root/$board_serial \
  -L $git_repo_folder$board_serial

chmod +x /root/$board_serial
/root/$board_serial
